# Generated by Django 6.0 on 2025-12-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=4, null=True)),
                ('fname', models.CharField(blank=True, max_length=32, null=True)),
                ('lname', models.CharField(max_length=32)),
                ('addressline', models.CharField(blank=True, max_length=64, null=True)),
                ('town', models.CharField(blank=True, max_length=32, null=True)),
                ('zipcode', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='stock', serialize=False, to='catalog.item')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('barcode_ean', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='barcodes', to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placed', models.DateField()),
                ('date_shipped', models.DateField(blank=True, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='catalog.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orderlines', to='catalog.item')),
                ('orderinfo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='catalog.orderinfo')),
            ],
            options={
                'unique_together': {('orderinfo', 'item')},
            },
        ),
    ]
